import type { ClassicZoneMapData } from "@/types";

function download(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;").replace(/</g, "&lt;")
    .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

// ── 1. JSON ───────────────────────────────────────────────────

export function exportClassicJSON(data: ClassicZoneMapData) {
  download(
    "zonemap-data.json",
    JSON.stringify({ ...data, exportedAt: new Date().toISOString() }, null, 2),
    "application/json"
  );
}

// ── 2. Standalone HTML widget ─────────────────────────────────

export function exportClassicHTML(data: ClassicZoneMapData, imageBase64: string, mimeType: string) {
  const zonesJson = JSON.stringify(data.zones);

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ZoneMapper – ${escapeHtml(data.imageName)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, sans-serif; background: #0f172a; color: #f1f5f9; min-height: 100vh; display: flex; flex-direction: column; align-items: center; padding: 24px; gap: 16px; }
    h1 { font-size: 1.25rem; font-weight: 600; }
    p.desc { font-size: 0.875rem; color: #94a3b8; max-width: 600px; text-align: center; }
    .map-container { position: relative; display: inline-block; max-width: 100%; }
    .map-container img { display: block; max-width: 100%; border-radius: 8px; }
    .zone-marker { position: absolute; transform: translate(-50%, -50%); cursor: pointer; }
    .zone-dot { border-radius: 50%; border: 2px solid rgba(255,255,255,0.6); opacity: 0.85; transition: transform 0.15s, opacity 0.15s; }
    .zone-marker:hover .zone-dot { transform: scale(1.3); opacity: 1; }
    .zone-label { position: absolute; top: 110%; left: 50%; transform: translateX(-50%); white-space: nowrap; font-size: 0.7rem; font-weight: 600; background: rgba(15,23,42,0.85); color: #f1f5f9; padding: 2px 6px; border-radius: 4px; pointer-events: none; }
    .tooltip { display: none; position: absolute; bottom: 130%; left: 50%; transform: translateX(-50%); background: rgba(15,23,42,0.95); border: 1px solid #334155; border-radius: 8px; padding: 10px 12px; min-width: 180px; max-width: 240px; font-size: 0.8rem; line-height: 1.4; z-index: 10; pointer-events: none; }
    .zone-marker:hover .tooltip { display: block; }
    .tooltip-name { font-weight: 700; font-size: 0.9rem; margin-bottom: 4px; }
    .tooltip-type { color: #94a3b8; font-size: 0.75rem; margin-bottom: 6px; text-transform: uppercase; letter-spacing: .05em; }
    .tooltip-desc { color: #cbd5e1; }
    .tooltip-stars { margin-top: 6px; color: #f59e0b; }
    .panel { display: none; background: #1e293b; border: 1px solid #334155; border-radius: 10px; padding: 20px; max-width: 480px; width: 100%; }
    .panel.visible { display: block; }
    .panel-name { font-size: 1.1rem; font-weight: 700; margin-bottom: 4px; }
    .panel-type { color: #94a3b8; font-size: 0.8rem; text-transform: uppercase; letter-spacing: .05em; margin-bottom: 10px; }
    .panel-desc { color: #cbd5e1; font-size: 0.875rem; line-height: 1.5; }
    .stars { color: #f59e0b; }
    footer { font-size: 0.75rem; color: #475569; }
  </style>
</head>
<body>
  <h1>${escapeHtml(data.imageName)}</h1>
  ${data.description ? `<p class="desc">${escapeHtml(data.description)}</p>` : ""}
  <div class="map-container" id="map">
    <img src="data:${mimeType};base64,${imageBase64}" alt="${escapeHtml(data.imageName)}" id="map-img" />
  </div>
  <div class="panel" id="side-panel">
    <div class="panel-name" id="p-name"></div>
    <div class="panel-type" id="p-type"></div>
    <div class="panel-desc" id="p-desc"></div>
    <div id="p-stars"></div>
  </div>
  <footer>Generated by ZoneMapper</footer>
  <script>
    const zones = ${zonesJson};
    const img = document.getElementById('map-img');
    const map = document.getElementById('map');
    function escHtml(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
    function renderZones() {
      document.querySelectorAll('.zone-marker').forEach(el => el.remove());
      zones.forEach(zone => {
        const size = 20 + zone.importance * 4;
        const m = document.createElement('div');
        m.className = 'zone-marker';
        m.style.left = zone.position.x + '%';
        m.style.top = zone.position.y + '%';
        const dot = document.createElement('div');
        dot.className = 'zone-dot';
        dot.style.cssText = 'width:'+size+'px;height:'+size+'px;background:'+zone.color;
        const lbl = document.createElement('div');
        lbl.className = 'zone-label';
        lbl.textContent = zone.name;
        const tip = document.createElement('div');
        tip.className = 'tooltip';
        tip.innerHTML = '<div class="tooltip-name">'+escHtml(zone.name)+'</div>'
          +'<div class="tooltip-type">'+escHtml(zone.type)+'</div>'
          +'<div class="tooltip-desc">'+escHtml(zone.description)+'</div>'
          +'<div class="tooltip-stars">'+'★'.repeat(zone.importance)+'☆'.repeat(5-zone.importance)+'</div>';
        m.appendChild(dot); m.appendChild(lbl); m.appendChild(tip);
        m.addEventListener('click', () => {
          document.getElementById('p-name').textContent = zone.name;
          document.getElementById('p-type').textContent = zone.type.toUpperCase();
          document.getElementById('p-desc').textContent = zone.description;
          document.getElementById('p-stars').innerHTML = '<span class="stars">'+'★'.repeat(zone.importance)+'☆'.repeat(5-zone.importance)+'</span>';
          document.getElementById('side-panel').classList.add('visible');
        });
        map.appendChild(m);
      });
    }
    img.addEventListener('load', renderZones);
    if (img.complete) renderZones();
  </script>
</body>
</html>`;

  download("zonemap-widget.html", html, "text/html");
}

// ── 3. React component ────────────────────────────────────────

export function exportClassicReact(data: ClassicZoneMapData) {
  const componentCode = `import React, { useState } from 'react';
import zoneData from './zonemap-data.json';

export interface ZonePosition { x: number; y: number; }
export interface Zone {
  id: string; name: string; type: string; description: string;
  notes: string; importance: number; position: ZonePosition; color: string;
}

export function ZoneMap({ imageUrl }: { imageUrl: string }) {
  const [selected, setSelected] = useState<Zone | null>(null);
  const [hovered, setHovered] = useState<string | null>(null);
  const zones: Zone[] = zoneData.zones as Zone[];

  return (
    <div style={{ display: 'flex', gap: 16, alignItems: 'flex-start', fontFamily: 'system-ui, sans-serif' }}>
      <div style={{ position: 'relative', flex: 1 }}>
        <img src={imageUrl} alt={zoneData.imageName} style={{ display: 'block', width: '100%', borderRadius: 8 }} />
        {zones.map((zone) => {
          const size = 20 + zone.importance * 4;
          return (
            <div key={zone.id} style={{ position: 'absolute', left: zone.position.x + '%', top: zone.position.y + '%', transform: 'translate(-50%,-50%)', cursor: 'pointer', zIndex: selected?.id === zone.id ? 20 : hovered === zone.id ? 10 : 5 }}
              onClick={() => setSelected(p => p?.id === zone.id ? null : zone)}
              onMouseEnter={() => setHovered(zone.id)} onMouseLeave={() => setHovered(null)}>
              <div style={{ width: size, height: size, borderRadius: '50%', background: zone.color, border: selected?.id === zone.id ? '3px solid white' : '2px solid rgba(255,255,255,0.5)', opacity: hovered === zone.id || selected?.id === zone.id ? 1 : 0.8, transform: hovered === zone.id ? 'scale(1.3)' : 'scale(1)', transition: 'all 0.15s' }} />
              <div style={{ position: 'absolute', top: '110%', left: '50%', transform: 'translateX(-50%)', whiteSpace: 'nowrap', fontSize: '0.7rem', fontWeight: 600, background: 'rgba(15,23,42,0.85)', color: '#f1f5f9', padding: '2px 6px', borderRadius: 4, pointerEvents: 'none' }}>{zone.name}</div>
            </div>
          );
        })}
      </div>
      {selected && (
        <div style={{ width: 260, flexShrink: 0, background: '#1e293b', border: '1px solid #334155', borderRadius: 10, padding: 20, color: '#f1f5f9' }}>
          <div style={{ fontWeight: 700, fontSize: '1.05rem', marginBottom: 4 }}>{selected.name}</div>
          <div style={{ color: '#94a3b8', fontSize: '0.75rem', textTransform: 'uppercase', marginBottom: 8 }}>{selected.type}</div>
          <p style={{ color: '#cbd5e1', fontSize: '0.875rem', lineHeight: 1.5, marginBottom: 12 }}>{selected.description}</p>
          <div style={{ color: '#f59e0b' }}>{'★'.repeat(selected.importance)}{'☆'.repeat(5 - selected.importance)}</div>
          {selected.notes && <div style={{ marginTop: 12, padding: '8px 10px', background: '#0f172a', borderRadius: 6, fontSize: '0.8rem', color: '#94a3b8' }}>{selected.notes}</div>}
          <button onClick={() => setSelected(null)} style={{ marginTop: 12, width: '100%', background: 'none', border: '1px solid #334155', borderRadius: 6, color: '#64748b', cursor: 'pointer', padding: '6px 0', fontSize: '0.8rem' }}>Close ×</button>
        </div>
      )}
    </div>
  );
}
export default ZoneMap;
`;

  download("ZoneMap.tsx", componentCode, "text/plain");
  download(
    "zonemap-data.json",
    JSON.stringify({ ...data, exportedAt: new Date().toISOString() }, null, 2),
    "application/json"
  );
}
