import type { ZoneMapData, ZoneShape } from "@/types";

// ─────────────────────────────────────────────────────────────
//  Export helpers
// ─────────────────────────────────────────────────────────────

/** Trigger a browser file download */
function download(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// ── 1. JSON export ────────────────────────────────────────────

export function exportJSON(data: ZoneMapData) {
  const payload = { ...data, exportedAt: new Date().toISOString() };
  download("zonemap-data.json", JSON.stringify(payload, null, 2), "application/json");
}

// ── 2. HTML image map export ─────────────────────────────────
//  Produces a standalone <img usemap> + <map><area> file.
//  Coordinates are converted from % to pixels using imageWidth/imageHeight.

export function exportHTMLMap(data: ZoneMapData, imageBase64: string, mimeType: string) {
  const { imageWidth: W, imageHeight: H } = data;

  const areas = data.zones.map((zone) => {
    const href = zone.href || "#";
    const target = zone.target || "_blank";
    const title = escapeHtml(zone.name);
    const coords = shapeToCoords(zone.shape, W, H);
    const shape = zone.shape.type === "circle" ? "circle"
      : zone.shape.type === "poly" ? "poly"
      : "rect";
    return `    <area shape="${shape}" coords="${coords}" href="${escapeHtml(href)}" target="${target}" title="${title}" alt="${title}" />`;
  }).join("\n");

  const mapName = "zonemap";
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(data.imageName)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, sans-serif; background: #0f172a; color: #f1f5f9; display: flex; flex-direction: column; align-items: center; padding: 24px; gap: 16px; }
    h1 { font-size: 1.25rem; font-weight: 600; }
    p.desc { font-size: 0.875rem; color: #94a3b8; max-width: 600px; text-align: center; }
    img { display: block; max-width: 100%; border-radius: 8px; }
    footer { font-size: 0.75rem; color: #475569; margin-top: 8px; }
  </style>
</head>
<body>
  <h1>${escapeHtml(data.imageName)}</h1>
  ${data.description ? `<p class="desc">${escapeHtml(data.description)}</p>` : ""}

  <img
    src="data:${mimeType};base64,${imageBase64}"
    alt="${escapeHtml(data.imageName)}"
    usemap="#${mapName}"
    width="${W}"
    height="${H}"
  />

  <map name="${mapName}">
${areas}
  </map>

  <footer>Generated by ZoneMapper</footer>
</body>
</html>`;

  download("zonemap-imagemap.html", html, "text/html");
}

// ── 3. Standalone HTML widget ─────────────────────────────────
//  Interactive SVG overlay with tooltips (no framework required).

export function exportHTML(data: ZoneMapData, imageBase64: string, mimeType: string) {
  const zonesJson = JSON.stringify(data.zones);
  const { imageWidth: W, imageHeight: H } = data;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ZoneMapper – ${escapeHtml(data.imageName)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, sans-serif; background: #0f172a; color: #f1f5f9; min-height: 100vh; display: flex; flex-direction: column; align-items: center; padding: 24px; gap: 16px; }
    h1 { font-size: 1.25rem; font-weight: 600; }
    p.desc { font-size: 0.875rem; color: #94a3b8; max-width: 600px; text-align: center; }
    .map-wrap { position: relative; display: inline-block; max-width: 100%; }
    .map-wrap img { display: block; max-width: 100%; border-radius: 8px; }
    svg.overlay { position: absolute; inset: 0; width: 100%; height: 100%; border-radius: 8px; }
    .tooltip {
      display: none; position: absolute; background: rgba(15,23,42,0.95);
      border: 1px solid #334155; border-radius: 8px; padding: 10px 12px;
      min-width: 180px; max-width: 240px; font-size: 0.8rem; line-height: 1.4;
      z-index: 20; pointer-events: none; color: #f1f5f9;
      transform: translate(-50%, -110%);
    }
    .tooltip.visible { display: block; }
    .tooltip-name { font-weight: 700; font-size: 0.9rem; margin-bottom: 4px; }
    .tooltip-type { color: #94a3b8; font-size: 0.75rem; text-transform: uppercase; letter-spacing: .05em; margin-bottom: 6px; }
    .tooltip-desc { color: #cbd5e1; }
    footer { font-size: 0.75rem; color: #475569; }
  </style>
</head>
<body>
  <h1>${escapeHtml(data.imageName)}</h1>
  ${data.description ? `<p class="desc">${escapeHtml(data.description)}</p>` : ""}

  <div class="map-wrap" id="wrap">
    <img src="data:${mimeType};base64,${imageBase64}" alt="${escapeHtml(data.imageName)}" id="map-img" />
    <svg class="overlay" id="svg-overlay"></svg>
    <div class="tooltip" id="tooltip"></div>
  </div>

  <footer>Generated by ZoneMapper</footer>

  <script>
    const zones = ${zonesJson};
    const svg = document.getElementById('svg-overlay');
    const tooltip = document.getElementById('tooltip');

    function escHtml(str) {
      return String(str).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
    }

    function svgEl(tag, attrs) {
      const el = document.createElementNS('http://www.w3.org/2000/svg', tag);
      Object.entries(attrs).forEach(([k,v]) => el.setAttribute(k, v));
      return el;
    }

    function renderZones() {
      svg.innerHTML = '';
      zones.forEach(zone => {
        let shape;
        const fill = zone.color + '33';
        const stroke = zone.color;
        const common = { fill, stroke, 'stroke-width': '1', cursor: 'pointer', 'data-id': zone.id };

        if (zone.shape.type === 'rect') {
          shape = svgEl('rect', { ...common, x: zone.shape.x + '%', y: zone.shape.y + '%', width: zone.shape.w + '%', height: zone.shape.h + '%' });
        } else if (zone.shape.type === 'circle') {
          shape = svgEl('ellipse', { ...common, cx: zone.shape.cx + '%', cy: zone.shape.cy + '%', rx: zone.shape.r + '%', ry: zone.shape.r + '%' });
        } else if (zone.shape.type === 'poly') {
          const pts = zone.shape.points.map(p => p.x + '%,' + p.y + '%').join(' ');
          shape = svgEl('polygon', { ...common, points: pts });
        }

        if (!shape) return;

        shape.addEventListener('mouseenter', (e) => {
          shape.setAttribute('fill', zone.color + '66');
          shape.setAttribute('stroke-width', '2');
          const r = svg.getBoundingClientRect();
          const cx = (e.clientX - r.left) / r.width * 100;
          const cy = (e.clientY - r.top) / r.height * 100;
          tooltip.style.left = cx + '%';
          tooltip.style.top = cy + '%';
          tooltip.innerHTML =
            '<div class="tooltip-name">' + escHtml(zone.name) + '</div>' +
            '<div class="tooltip-type">' + escHtml(zone.type) + '</div>' +
            '<div class="tooltip-desc">' + escHtml(zone.description) + '</div>';
          tooltip.classList.add('visible');
        });
        shape.addEventListener('mouseleave', () => {
          shape.setAttribute('fill', zone.color + '33');
          shape.setAttribute('stroke-width', '1');
          tooltip.classList.remove('visible');
        });
        if (zone.href) {
          shape.style.cursor = 'pointer';
          shape.addEventListener('click', () => window.open(zone.href, zone.target || '_blank'));
        }

        svg.appendChild(shape);

        // Label
        let lx = 50, ly = 50;
        if (zone.shape.type === 'rect') { lx = zone.shape.x + zone.shape.w / 2; ly = zone.shape.y + zone.shape.h / 2; }
        else if (zone.shape.type === 'circle') { lx = zone.shape.cx; ly = zone.shape.cy; }
        else if (zone.shape.type === 'poly' && zone.shape.points.length > 0) {
          lx = zone.shape.points.reduce((s,p) => s + p.x, 0) / zone.shape.points.length;
          ly = zone.shape.points.reduce((s,p) => s + p.y, 0) / zone.shape.points.length;
        }
        const label = svgEl('text', {
          x: lx + '%', y: ly + '%',
          'text-anchor': 'middle', 'dominant-baseline': 'central',
          'font-size': '1.2%', 'font-weight': '600',
          fill: 'white', style: 'pointer-events:none;user-select:none;',
        });
        label.textContent = zone.name.length > 16 ? zone.name.slice(0,14) + '…' : zone.name;
        svg.appendChild(label);
      });
    }

    const img = document.getElementById('map-img');
    img.addEventListener('load', renderZones);
    if (img.complete) renderZones();
  </script>
</body>
</html>`;

  download("zonemap-widget.html", html, "text/html");
}

// ── 4. Image Map snippet export ──────────────────────────────
//  Produces only the <img usemap> + <map><area> snippet,
//  referencing the original filename (no base64 embedded).
//  Coordinates are converted from % to pixels.

export function exportImageMapSnippet(data: ZoneMapData) {
  const { imageWidth: W, imageHeight: H, imageName } = data;

  const areas = data.zones.map((zone) => {
    const coords = shapeToCoords(zone.shape, W, H);
    const shape = zone.shape.type === "circle" ? "circle"
      : zone.shape.type === "poly" ? "poly"
      : "rect";
    const title = escapeHtml(zone.name);
    const href  = escapeHtml(zone.href || "");
    const target = zone.target || "";
    return `    <area target="${target}" alt="${title}" title="${title}" href="${href}" coords="${coords}" shape="${shape}">`;
  }).join("\n");

  const snippet =
`<!-- Image Map Generated by https://zonemapper.kaanmkt.com -->
<img src="${escapeHtml(imageName)}" usemap="#image-map">

<map name="image-map">
${areas}
</map>`;

  download(`${imageName.replace(/\.[^.]+$/, "")}-imagemap.txt`, snippet, "text/plain");
}

// ── 5. React component export ────────────────────────────────

export function exportReact(data: ZoneMapData) {
  const componentCode = `import React, { useState } from 'react';
import zoneData from './zonemap-data.json';

// ZoneMap — drop-in React component
// Props:
//   imageUrl: URL or import of the background image

export function ZoneMap({ imageUrl }: { imageUrl: string }) {
  const [hovered, setHovered] = useState<string | null>(null);

  return (
    <div style={{ position: 'relative', display: 'inline-block', maxWidth: '100%', fontFamily: 'system-ui, sans-serif' }}>
      <img src={imageUrl} alt={zoneData.imageName} style={{ display: 'block', width: '100%', borderRadius: 8 }} />
      <svg style={{ position: 'absolute', inset: 0, width: '100%', height: '100%' }}>
        {zoneData.zones.map((zone) => {
          const fill = hovered === zone.id ? zone.color + '66' : zone.color + '33';
          const sw = hovered === zone.id ? '2' : '1';
          const commonProps = {
            fill, stroke: zone.color, strokeWidth: sw, cursor: zone.href ? 'pointer' : 'default',
            onMouseEnter: () => setHovered(zone.id),
            onMouseLeave: () => setHovered(null),
            onClick: zone.href ? () => window.open(zone.href, zone.target) : undefined,
          };
          let shape = null;
          if (zone.shape.type === 'rect') {
            shape = <rect key={zone.id} x={zone.shape.x + '%'} y={zone.shape.y + '%'} width={zone.shape.w + '%'} height={zone.shape.h + '%'} {...commonProps} />;
          } else if (zone.shape.type === 'circle') {
            shape = <ellipse key={zone.id} cx={zone.shape.cx + '%'} cy={zone.shape.cy + '%'} rx={zone.shape.r + '%'} ry={zone.shape.r + '%'} {...commonProps} />;
          } else if (zone.shape.type === 'poly') {
            const pts = zone.shape.points.map(p => p.x + '%,' + p.y + '%').join(' ');
            shape = <polygon key={zone.id} points={pts} {...commonProps} />;
          }
          return shape;
        })}
      </svg>
    </div>
  );
}

export default ZoneMap;
`;

  download("ZoneMap.tsx", componentCode, "text/plain");
  download("zonemap-data.json", JSON.stringify({ ...data, exportedAt: new Date().toISOString() }, null, 2), "application/json");
}

// ── Utilities ────────────────────────────────────────────────

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Convert a ZoneShape from % coords to pixel coords string for <area coords="…"> */
function shapeToCoords(shape: ZoneShape, W: number, H: number): string {
  const px = (v: number, dim: number) => Math.round((v / 100) * dim);
  if (shape.type === "rect") {
    const x1 = px(shape.x, W);
    const y1 = px(shape.y, H);
    const x2 = px(shape.x + shape.w, W);
    const y2 = px(shape.y + shape.h, H);
    return `${x1},${y1},${x2},${y2}`;
  }
  if (shape.type === "circle") {
    return `${px(shape.cx, W)},${px(shape.cy, H)},${px(shape.r, Math.min(W, H))}`;
  }
  if (shape.type === "poly") {
    return shape.points.map((p) => `${px(p.x, W)},${px(p.y, H)}`).join(",");
  }
  return "";
}
