import type { ZoneMapData } from "@/types";

/** Sample data used in the /help page previews */
export const SAMPLE_DATA: ZoneMapData = {
  imageType: "Architectural floor plan",
  description: "A residential apartment floor plan showing common living areas and private rooms.",
  imageName: "sample-floor-plan.png",
  imageWidth: 800,
  imageHeight: 600,
  exportedAt: new Date().toISOString(),
  zones: [
    {
      id: "zone_1",
      name: "Living Room",
      type: "room",
      description: "Main communal living area with seating and entertainment",
      notes: "",
      href: "",
      target: "_blank",
      color: "#f97316",
      shape: { type: "rect", x: 5, y: 10, w: 40, h: 45 },
    },
    {
      id: "zone_2",
      name: "Master Bedroom",
      type: "room",
      description: "Primary bedroom with en-suite bathroom access",
      notes: "",
      href: "",
      target: "_blank",
      color: "#ec4899",
      shape: { type: "rect", x: 55, y: 5, w: 40, h: 40 },
    },
    {
      id: "zone_3",
      name: "Kitchen",
      type: "room",
      description: "Fully equipped kitchen with cooking and dining space",
      notes: "",
      href: "",
      target: "_blank",
      color: "#eab308",
      shape: { type: "rect", x: 5, y: 60, w: 35, h: 35 },
    },
    {
      id: "zone_4",
      name: "Hallway",
      type: "road",
      description: "Connecting corridor between rooms",
      notes: "",
      href: "",
      target: "_self",
      color: "#94a3b8",
      shape: { type: "rect", x: 45, y: 10, w: 10, h: 85 },
    },
    {
      id: "zone_5",
      name: "Bathroom",
      type: "room",
      description: "Main bathroom with shower and bathtub",
      notes: "",
      href: "",
      target: "_blank",
      color: "#06b6d4",
      shape: { type: "rect", x: 55, y: 55, w: 25, h: 30 },
    },
    {
      id: "zone_6",
      name: "Garden",
      type: "area",
      description: "Outdoor green space with patio",
      notes: "",
      href: "",
      target: "_blank",
      color: "#22c55e",
      shape: { type: "rect", x: 5, y: 5, w: 35, h: 5 },
    },
  ],
};
